import { Link } from "react-router-dom";
import SectionTitle from "../component/SectionTitle";

// Import compoent
import ComponentCard from "../component/ComponentCard";

// Import data
import { components } from "../data/data";


/**
 * This file for dolalak page, contains name, images and description about
 * dolalak component or attributes.
 * @returns 
 */
const Dolalak = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16">


      {/* Link to go back */}
      <Link to="/" className="text-gold-dark hover:text-ink text-sm">
        Back to home...
      </Link>


      <div className="mt-6">
        <SectionTitle align="center">
          Components / Attributes of the Dolalak Dance
        </SectionTitle>

        <p>
          The following are some of the components or attributes used by dancers
          in the Dolalak dance performance.
        </p>
        <br />

        {/* Get data from data.js and then show */}
        <div className="space-y-6">
          {components.map((c, i) => (
            <ComponentCard key={i} {...c} />
          ))}
        </div>
        <br />

        <h4>
          <i>Image generated by AI</i>
        </h4>
        <br />

      </div>
    </div>
  );
};

export default Dolalak;